"""empty message

Revision ID: f3e9fb94b81b
Revises: 
Create Date: 2023-01-26 23:15:41.460286

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3e9fb94b81b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medicine',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=30), nullable=True),
    sa.Column('prescricao', sa.String(length=30), nullable=True),
    sa.Column('fabricante', sa.String(length=30), nullable=True),
    sa.Column('validade', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=30), nullable=True),
    sa.Column('idade', sa.Integer(), nullable=True),
    sa.Column('password_hash', sa.LargeBinary(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('checklist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('remedio', sa.String(length=30), nullable=True),
    sa.Column('id_remedio', sa.Integer(), nullable=True),
    sa.Column('qnt_estoque', sa.Integer(), nullable=True),
    sa.Column('qnt_ideal', sa.Integer(), nullable=True),
    sa.Column('comprar', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_remedio'], ['medicine.id'], ),
    sa.ForeignKeyConstraint(['remedio'], ['medicine.nome'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('checklist')
    op.drop_table('users')
    op.drop_table('medicine')
    # ### end Alembic commands ###
